### ISSUE TITLE
Change default justbytes string representation to avoid prefix

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#78]
See #77, I think for our purposes we'd like to turn off the prefixes, since storage sizes are so large the rounded values are ok.

Sounds like there's a way to configure justbytes globally, which would be best, to minimize the code needed at each use of the library.

**Comment by mulkieran** [comment]
I do not think that the whole issue is about size. Real users might want to know if some value is exactly 1 GiB, or just shy of 1 GiB (and there is metadata taking up the rest or something). It's not hard to change, but I don't think it should be dismissed too lightly because it is unfamiliar. Storage is a logical quantity, not a physical quantity and we should really allow ourselves to imagine that it should be viewed differently.

Examples of physical quantities are length, volume, and other things that are measured, with some amount of imprecision. As Charles Seife points out in his book "Proofiness", votes, also, are measured quantities, with some amount of imprecision, although everybody acts as if they are not. Anyway, bytes are unusual because they are absolutely precise quantities. With physical quantities, if we have one really big quantity and some very small quantity, if the small quantity is small enough, we ignore it. If we do that in storage, we overwrite our metadata. Whoops.

**Comment by agrover** [comment]
This is a UI issue -- how much info is appropriate to show the user? This is unrelated to Stratis's internal calculations, which are responsible for not overwriting metadata, and which of course are precise.

Why does the user care if they have 3.004 GiB available instead of 3.00 GiB? We could report one digit after the decimal -- 3.0 GiB or 2.9 GiB. The user hardly cares about the first digit, much less the second, so why have a special symbol for saying something about the third digit?

**Comment by mulkieran** [comment]
What makes you believe that the user "doesn't care" about x, and therefore surely "doesn't care" about y? Maybe you're mistaking stolid acceptance for indifference.

**Comment by agrover** [comment]
Because I'm also a user 😃 and I don't think additional precision is useful for the same reason that gas gauges only show fractions of a tank, clocks don't show milliseconds (or even usually seconds), and battery remaining on my phone is given only in percentage (or even usually just a small 5-state icon). The user only usually (99 times out of 100) needs a certain level of precision to get a sense of the value.

For those other cases where a user wants more, that's where #79 comes in... we can give an answer with the greatest possible precision -- in bytes? -- and still keep the default case as simple as possible.

**Comment by mulkieran** [comment]
Those are all physical quantities, hence bad analogies. _That is my point._ A logical quantity would be the number of mailboxes in a given town, perhaps, since people generally like to get all of their mail and none of other peoples. But storage ranges exist in their own special world and don't have many good analogies.

I do not care what configuration parameters we choose as the default for Stratis, so long as:
* We do not claim that they are the best or the most natural. I have experimented w/ more ways of displaying storage ranges than anybody else in the whole world, and I am in the best position to know that what we are choosing is _not_ the best or the most natural.
* The analogies with physical quantities are set aside. They are ubiquitous and deceptive. I am in a better position to defend this statement than a lot of people working in software, because I received an undergraduate engineering degree (Civil) and the measurement and representation of physical quantities is actually an important consideration in such a discipline.
* We agree that, in the fullness of time, stratis-cli will have its own configuration file, where discriminating users can set up display of storage ranges in whatever manner they prefer. That is somewhat related to #79, anyway.

**Comment by agrover** [comment]
Ok. Sounds like there may be further discussion in the future but you're ok with setting the default global justbytes option `use_prefix` to false for now.

What's the best way to do this? From looking at the docs at http://pythonhosted.org/justbytes/ I think I can see how to do it on a case-by-case basis, but not globally. Or should we just have a helper conversion function that always invokes justbytes with the specified config?

**Comment by mulkieran** [comment]
I remember that I wrote some sort of global way to do this. I'll check.
